server:
  port: 0

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}} 

  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    fetch-registry: true

