server:
  port: 8765

info:
  component: Zuul Server

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    clientes: /clientes/**