info:
  component: Zuul Server

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    clientes:
      path: /clientes/**
    pedidos:
      path: /pedidos/**
    user:
      path: /user/**
  sensitiveHeaders: Cookie,Set-Cookie
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
